version: '3'
services: 
  giropops-senhas:
    image: linuxtips/giropops-senhas:1.0 
    ports:
      - "5000:5000"
    networks:
      - giropops
    environment:
      REDIS_HOST: redis
    volumes: 
      - strigus:/strigus 
  redis: 
    image: redis
    ports:
      - "6379:6379"
    networks:
      - giropops 
    volumes: 
      - strigus:/strigus
networks:
  giropops:
    driver: bridge
volumes: 
  strigus:
    
    
